CREATE DATABASE IF NOT EXISTS mydatabase;
USE mydatabase;

CREATE TABLE IF NOT EXISTS mytable (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    nim VARCHAR(20) NOT NULL,
    checkbox BOOLEAN NOT NULL,
    radio VARCHAR(50) NOT NULL,
    browser VARCHAR(50) NOT NULL,
    ip_address VARCHAR(15) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);